import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter, Sora } from "next/font/google";
import "./globals.css";

const sora = Bricolage_Grotesque({
  variable: "--Bricolage_Grotesque",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${sora.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
